package Ventanas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import primitiva_interfaz.Primitiva;


/**
 *
 * @author danie
 */
public class Interfaz extends javax.swing.JFrame {

  ArrayList<Integer> numeroGanador = new ArrayList<>(8);

  /**
   * Creates new form Interfaz
   */
  public Interfaz() {
    initComponents();
    //centramos al medio de la pantalla
    this.setLocationRelativeTo(null);

  }

  /**
   * This method is called from within
   * the constructor to initialize the
   * form. WARNING: Do NOT modify this
   * code. The content of this method is
   * always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToggleButton1 = new javax.swing.JToggleButton();
    Salir = new javax.swing.JButton();
    Logo = new javax.swing.JLabel();
    GenerarNumero = new javax.swing.JPanel();
    BotonGenerarN = new javax.swing.JButton();
    TextoGenerarN = new javax.swing.JTextField();
    Fondo = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();

    jToggleButton1.setText("jToggleButton1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Salir.setBackground(new java.awt.Color(40, 127, 51));
    Salir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
    Salir.setText("Salir");
    Salir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SalirActionPerformed(evt);
      }
    });
    getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

    Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/La_Primitiva.png"))); // NOI18N
    getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 490, 280));

    GenerarNumero.setBackground(new java.awt.Color(102, 102, 102));
    GenerarNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    BotonGenerarN.setBackground(new java.awt.Color(40, 127, 51));
    BotonGenerarN.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    BotonGenerarN.setText("Generar Numero");
    BotonGenerarN.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonGenerarNActionPerformed(evt);
      }
    });

    TextoGenerarN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    TextoGenerarN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    TextoGenerarN.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextoGenerarNActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout GenerarNumeroLayout = new javax.swing.GroupLayout(GenerarNumero);
    GenerarNumero.setLayout(GenerarNumeroLayout);
    GenerarNumeroLayout.setHorizontalGroup(
      GenerarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenerarNumeroLayout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(TextoGenerarN, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(BotonGenerarN)
        .addContainerGap())
    );
    GenerarNumeroLayout.setVerticalGroup(
      GenerarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(GenerarNumeroLayout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(GenerarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BotonGenerarN)
          .addComponent(TextoGenerarN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(38, Short.MAX_VALUE))
    );

    getContentPane().add(GenerarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 320, -1));

    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
    Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

    jButton1.setText("jButton1");
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_SalirActionPerformed

  private void TextoGenerarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoGenerarNActionPerformed

  }//GEN-LAST:event_TextoGenerarNActionPerformed

  private void BotonGenerarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarNActionPerformed
    /*CODIGO ANIADIDO*/
    Primitiva p = new Primitiva();
    numeroGanador = p.numeroGanador();
    this.TextoGenerarN.setText(numeroGanador.toString());
    /*FIN CODIGO ANIADIDO*/
  }//GEN-LAST:event_BotonGenerarNActionPerformed

  /**
   * @param args the command line
   * arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Interfaz().setVisible(true);
      }
    });

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BotonGenerarN;
  private javax.swing.JLabel Fondo;
  private javax.swing.JPanel GenerarNumero;
  private javax.swing.JLabel Logo;
  private javax.swing.JButton Salir;
  private javax.swing.JTextField TextoGenerarN;
  private javax.swing.JButton jButton1;
  private javax.swing.JToggleButton jToggleButton1;
  // End of variables declaration//GEN-END:variables
}
